#!/bin/bash

# exit when any command fails
set -e

DEBIAN_FRONTEND=noninteractive

# create a tun device
mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 600 /dev/net/tun

: ${GOST_ARGS:="-L :1080"}

function start_gost_if_need() {
  if pgrep -x "gost" >/dev/null; then
    return
  fi

  # start the proxy
  nohup gost $GOST_ARGS &
}

function register_if_need() {
  if [ -f /var/lib/cloudflare-warp/reg.json ]; then
    return
  fi

  # if /var/lib/cloudflare-warp/reg.json not exists, register the warp client
  warp-cli register && echo "Warp client registered!"
  # if a license key is provided, register the license
  if [ -n "$WARP_LICENSE_KEY" ]; then
    echo "License key found, registering license..."
    warp-cli set-license "$WARP_LICENSE_KEY" && echo "Warp license registered!"
  fi
}

function start_warp_svc_if_need() {
  if pgrep -x "warp-svc" >/dev/null; then
    return
  fi

  nohup warp-svc >/dev/null &

  while true; do

    if ! warp-cli status 2>/dev/null 1>/dev/null; then

      echo "warp 服务未启动，将在 5 秒后重试"
      sleep 5
      continue

    fi

    echo "warp 服务启动成功"
    break

  done

  register_if_need

  warp-cli connect

}

#########################################################

while true; do
  start_warp_svc_if_need

  start_gost_if_need

  sleep 10

done
