#!/bin/bash

# exit when any command fails
set -e

DEBIAN_FRONTEND=noninteractive

: ${WARP_PROXY_PORT:=1080}

function register_if_need() {
  if [ -f /var/lib/cloudflare-warp/reg.json ]; then
    return
  fi

  # if /var/lib/cloudflare-warp/reg.json not exists, register the warp client
  warp-cli register && echo "Warp client registered!"
  # if a license key is provided, register the license
  if [ -n "$WARP_LICENSE_KEY" ]; then
    echo "License key found, registering license..."
    warp-cli set-license "$WARP_LICENSE_KEY" && echo "Warp license registered!"
  fi
}

function wait_for_warp_ready() {
  while true; do

    if ! warp-cli status 2>/dev/null 1>/dev/null; then

      echo "warp 服务未启动，将在 5 秒后重试"
      sleep 5
      continue

    fi

    echo "warp 服务启动成功"
    break

  done
}

function run_after_warp_ready() {
  wait_for_warp_ready

  register_if_need

  warp-cli connect

  # 设置工作模式为Proxy
  warp-cli set-mode proxy

  # 设置Socks5工作端口， 默认为1080
  warp-cli set-proxy-port $WARP_PROXY_PORT
}

#########################################################

run_after_warp_ready &

warp-svc | grep -v DEBUG
