name: Build and Publish Docker Image

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYYMMDD-HHmmss"
                
      
      - name: Prepare environment variables
        id: prepare
        run: |
          REPO_NAME=$(echo "warp-docker" | sed 's/-docker//') && echo "docker_image=${{ secrets.DOCKER_HUB_USER }}/${REPO_NAME}" >> $GITHUB_OUTPUT

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          # build-args: |
          #   "OLS_VERSION=${{ matrix.OLS_VERSION }}"
          #   "PHP_VERSION=${{ matrix.PHP_VERSION }}"
          tags: ${{  steps.prepare.outputs.docker_image }}, ${{  steps.prepare.outputs.docker_image }}:${{ steps.time.outputs.time }}
